- name: "HF-Node"
  type: vless
  server: yeehang-node.hf.space
  port: 443
  uuid: 5efabea4-f6d4-91fd-b8f0-17e004c89c60
  encryption: none  # 补全必选的加密字段
  udp: true
  tls: true
  network: ws
  servername: yeehang-node.hf.space
  ws-opts:
    path: /
    headers:
      Host: yeehang-node.hf.space
